from tkinter import *
root = Tk()
root.geometry("655x333")
f1 = Frame(root, bg="darkgray", borderwidth=20, relief=GROOVE)
f1.pack(side=LEFT, fill="y")
f2 = Frame(root, borderwidth=20, bg="purple", relief=GROOVE)
f2.pack(side=TOP, fill="x")
l = Label(f1, text="Project Tkinter - Pycharm",bg="white",fg="black",font="Helvetica 16 bold",padx=22)
l.pack( pady=142)
l = Label(f2, text="Welcome to sublime text", bg="white",font="Helvetica 20 bold", fg="black", pady=22,padx=10)
l.pack()
root.mainloop()